theme: jekyll-theme-minimal
title: flubber's cool homepage
description: heyo guys!!

body {  background-color: #ADD8E6; } 

<img src="/wp-content/uploads/file:///C:/Users/soyfr/Downloads/spr_playerN_idle/spr_playerN_idle_0.png">
